;;; org-scribe-planner-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.
;; Regenerate with: emacs --batch --eval
;;   "(loaddefs-generate \"<repo>/planning\" \"<repo>/planning/org-scribe-planner-autoloads.el\")"

;;; Code:



;;; Generated autoloads from org-scribe-planner.el

(autoload 'org-scribe-planner-new-plan "org-scribe-planner"
"Create a new writing plan interactively." t)
(autoload 'org-scribe-planner-load-plan "org-scribe-planner"
"Load an existing writing plan and set it as the active plan." t)
(autoload 'org-scribe-planner-sync-agenda "org-scribe-planner"
"Sync active writing plan to org-agenda." t)
(autoload 'org-scribe-planner-update-progress "org-scribe-planner"
"Update the current word count for the active writing plan." t)
(autoload 'org-scribe-planner-update-daily-word-count "org-scribe-planner"
"Update the actual word count for a specific day in the active plan." t)
(autoload 'org-scribe-planner-today "org-scribe-planner"
"Log today's word count to the active plan without extra prompts.
Pre-fills today's date, asks for a word count (using
`org-scribe-planner-wordcount-function' when set) and an optional note,
then saves immediately.  No recalculation prompt is shown." t)
(autoload 'org-scribe-planner-adjust-remaining-plan "org-scribe-planner"
"Recalculate daily target for remaining days based on progress.
This command keeps your end date and total word goal fixed, and adjusts
only the daily target for remaining working days based on your actual
cumulative progress so far." t)
(autoload 'org-scribe-planner-recalculate "org-scribe-planner"
"Recalculate the active writing plan with new parameters." t)
(autoload 'org-scribe-planner-show-milestones "org-scribe-planner"
"Show milestone dates for the active writing plan with actual and expected dates." t)
(autoload 'org-scribe-planner-show-current-plan "org-scribe-planner"
"Display the calendar for the currently active plan.
If no plan is active, prompt to load one." t)
(autoload 'org-scribe-planner-current-plan-info "org-scribe-planner"
"Show information about the currently active plan." t)
(register-definition-prefixes "org-scribe-planner" '("org-scribe-planner-"))


;;; Generated autoloads from org-scribe-planner-dashboards.el

(autoload 'org-scribe-planner-show-progress-dashboard "org-scribe-planner-dashboards"
"Display a comprehensive progress dashboard for the active plan." t)
(autoload 'org-scribe-planner-show-burndown "org-scribe-planner-dashboards"
"Display burndown chart for the active plan.
Prefers gnuplot version if available, falls back to ASCII.
With prefix argument FORCE-ASCII, always use ASCII version.

(fn &optional FORCE-ASCII)" t)
(autoload 'org-scribe-planner-show-burndown-ascii "org-scribe-planner-dashboards"
"Display ASCII burndown chart (text-based)." t)
(autoload 'org-scribe-planner-show-burndown-gnuplot "org-scribe-planner-dashboards"
"Display burndown chart using gnuplot (high quality)." t)
(autoload 'org-scribe-planner-show-cumulative-progress "org-scribe-planner-dashboards"
"Display cumulative progress chart using gnuplot." t)
(autoload 'org-scribe-planner-show-progress-dashboard-svg "org-scribe-planner-dashboards"
"Display enhanced progress dashboard with SVG indicators." t)
(autoload 'org-scribe-planner-show-velocity "org-scribe-planner-dashboards"
"Display velocity statistics and trends for the active plan." t)
(autoload 'org-scribe-planner-show-performance-analytics "org-scribe-planner-dashboards"
"Display comprehensive performance analytics for the active plan.
Shows day-of-week patterns, consistency scores, and target achievement rates." t)
(autoload 'org-scribe-planner-show-velocity-trends "org-scribe-planner-dashboards"
"Display comprehensive velocity trend analysis for the active plan.
Shows multi-window averages, acceleration/deceleration, and projections." t)
(autoload 'org-scribe-planner-show-velocity-chart "org-scribe-planner-dashboards"
"Display velocity bar chart using chart.el for the active plan.
Shows daily word counts over time with a 7-day moving average." t)
(autoload 'org-scribe-planner-show-multi-metric-dashboard "org-scribe-planner-dashboards"
"Display comprehensive multi-metric dashboard combining key metrics.
Shows progress, velocity, performance, and projections in one unified view." t)
(autoload 'org-scribe-planner-show-split-dashboards "org-scribe-planner-dashboards"
"Display multiple dashboards in split windows for comprehensive overview.
Shows progress, velocity, and performance dashboards side by side." t)
(autoload 'org-scribe-planner-show-heatmap "org-scribe-planner-dashboards"
"Display calendar heatmap showing writing consistency." t)
(autoload 'org-scribe-planner-dashboards-menu "org-scribe-planner-dashboards"
"Show dashboard selection menu." t)
(autoload 'org-scribe-planner-show-all-dashboards "org-scribe-planner-dashboards"
"Display all dashboards in split windows." t)
(register-definition-prefixes "org-scribe-planner-dashboards" '("org-scribe-planner-"))

;;; End of scraped data

(provide 'org-scribe-planner-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-scribe-planner-autoloads.el ends here
